FROM sbtscala/scala-sbt:eclipse-temurin-25.0.1_8_1.12.11_3.8.3 as builder

WORKDIR /app
COPY . .

ENV MAIN_CLASS=assignment4.App
RUN sbt "set cluster / assembly / mainClass := Some(\"$MAIN_CLASS\")" "cluster / assembly"

FROM eclipse-temurin:25.0.3_9-jre

WORKDIR /app
COPY --from=builder /app/target/scala-3.8.3/cluster-assembly-0.1.0-SNAPSHOT.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
